version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: tap
    versions:
    - 15.0.1
    - 15.0.2
    - 15.0.4
  - dependency-name: fastify-cookie
    versions:
    - 5.1.0
    - 5.2.0
